/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.LoginDao;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Login;

/**
 *
 * @author aluno
 */
public class jfrmTelaInicial extends javax.swing.JFrame {

    private int flag;

    /**
     * Creates new form jfrmTelaCadastro
     */
    public jfrmTelaInicial() {
        initComponents();

        this.setTitle("Login");
        this.setSize(806, 537);
        this.setLocationRelativeTo(null);

        // listarUsuarios();
        // listarUsuariosLogados();
        this.flag = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jBConcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCasdastro = new javax.swing.JMenu();
        jMenuItemUsuarioCadastro = new javax.swing.JMenuItem();
        jMenuItemPetCadastro = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemUsuarioEditar = new javax.swing.JMenuItem();
        relatorio = new javax.swing.JMenu();
        jMenuItemRelatorio = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador Financeiro");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema Exemplo"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jBConcluir.setText("Fechar");
        jBConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcluirActionPerformed(evt);
            }
        });

        jMenuCasdastro.setText("Casdastro");

        jMenuItemUsuarioCadastro.setText("Usuário");
        jMenuItemUsuarioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioCadastroActionPerformed(evt);
            }
        });
        jMenuCasdastro.add(jMenuItemUsuarioCadastro);

        jMenuItemPetCadastro.setText("Pet");
        jMenuItemPetCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPetCadastroActionPerformed(evt);
            }
        });
        jMenuCasdastro.add(jMenuItemPetCadastro);

        jMenuBar1.add(jMenuCasdastro);

        jMenuEditar.setText("Editar");

        jMenuItemUsuarioEditar.setText("Usuário");
        jMenuItemUsuarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioEditarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemUsuarioEditar);

        jMenuBar1.add(jMenuEditar);

        relatorio.setText("Relatorio");

        jMenuItemRelatorio.setText("Gerar Relatorio");
        jMenuItemRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioActionPerformed(evt);
            }
        });
        relatorio.add(jMenuItemRelatorio);

        jMenuBar1.add(relatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBConcluir)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBConcluir)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUsuarioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioCadastroActionPerformed
        // TODO add your handling code here:
        jfrmCadastroUsuario cadastroUsuario = new jfrmCadastroUsuario();
        cadastroUsuario.show();
    }//GEN-LAST:event_jMenuItemUsuarioCadastroActionPerformed
    
    
    
    private void jBConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcluirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBConcluirActionPerformed

    private void jMenuItemUsuarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioEditarActionPerformed
        // TODO add your handling code here:
        jfrmEditarUsuario editarUsuario = new jfrmEditarUsuario();
        editarUsuario.show();
    }//GEN-LAST:event_jMenuItemUsuarioEditarActionPerformed

    private void jMenuItemRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioActionPerformed
        // TODO add your handling code here:

        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd_MM_yyyy");
        String dataAtual = String.valueOf(formatador.format(data));
        try {
            PdfWriter.getInstance(document, new FileOutputStream("Relatório " + dataAtual + ".pdf"));
            Font fontNegrita = new Font(Font.FontFamily.HELVETICA, 5, Font.BOLD);
            Font fontNegritaP = new Font(Font.FontFamily.HELVETICA, 9, Font.BOLD);
            Font font = new Font(Font.FontFamily.HELVETICA, 8);
            Font fontConteudoTabela = new Font(Font.FontFamily.HELVETICA, 5);

            document.open();
            document.setPageSize(PageSize.A3);
            Paragraph titulo = new Paragraph("TITULO", fontNegritaP);
            Paragraph subtitulo = new Paragraph("SUBTITULO", font);
            titulo.setAlignment(Element.ALIGN_CENTER);
            subtitulo.setAlignment(Element.ALIGN_CENTER);

            document.add(titulo);
            document.add(subtitulo);
            document.add(new Paragraph("\n"));

            PdfPTable tabela = new PdfPTable(new float[]{60f, 40f, 20f});
            tabela.setTotalWidth(550);
            tabela.setLockedWidth(true);

            PdfPCell c1 = new PdfPCell(new Phrase("COLUNA 1", fontNegrita));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabela.addCell(c1);

            c1 = new PdfPCell(new Phrase("COLUNA 2", fontNegrita));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabela.addCell(c1);

            c1 = new PdfPCell(new Phrase("COLUNA 3", fontNegrita));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabela.addCell(c1);

            ArrayList<Login> loginArray = new ArrayList<Login>();

            LoginDao loginDao = new LoginDao();
            try {
                loginArray = loginDao.listar("");
            } catch (Exception ex) {
                Logger.getLogger(jfrmTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }

            for (int i = 0; i < loginArray.size(); i++) {

                PdfPCell c = new PdfPCell(new Phrase(String.valueOf(loginArray.get(i).getId()), fontConteudoTabela));
                c.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabela.addCell(c);

                c = new PdfPCell(new Phrase(loginArray.get(i).getUsuario(), fontConteudoTabela));
                c.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabela.addCell(c);

                c = new PdfPCell(new Phrase("Coluna 3", fontConteudoTabela));
                c.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabela.addCell(c);

            }
            document.add(tabela);
            document.add(new Paragraph("\n"));
            Paragraph emicao = new Paragraph("EMISSÃO: " + dataAtual, font);
            emicao.setAlignment(Element.ALIGN_RIGHT);
            document.add(new Paragraph(emicao));
            document.close();

        } catch (DocumentException ex) {
            System.out.println("Error:" + ex);
        } catch (FileNotFoundException ex) {
            System.out.println("Error:" + ex);
        } finally {
            document.close();
        }

        try {
            Desktop.getDesktop().open(new File("Relatório " + dataAtual + ".pdf"));
        } catch (IOException ex) {
            System.out.println("Error:" + ex);
        }


    }//GEN-LAST:event_jMenuItemRelatorioActionPerformed

    private void jMenuItemPetCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPetCadastroActionPerformed
        // TODO add your handling code here:
        jfrmCadastroPet cadastroPet = new jfrmCadastroPet();
        cadastroPet.show();
      
        

    }//GEN-LAST:event_jMenuItemPetCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConcluir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCasdastro;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuItemPetCadastro;
    private javax.swing.JMenuItem jMenuItemRelatorio;
    private javax.swing.JMenuItem jMenuItemUsuarioCadastro;
    private javax.swing.JMenuItem jMenuItemUsuarioEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu relatorio;
    // End of variables declaration//GEN-END:variables
    
}




