/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.LoginDao;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Login;

/**
 *
 * @author aluno
 */
public class jfrmTelaInicial extends javax.swing.JFrame {

    private int flag;

    /**
     * Creates new form jfrmTelaCadastro
     */
    public jfrmTelaInicial() {
        initComponents();

        this.setTitle("Login");
        this.setSize(806, 537);
        this.setLocationRelativeTo(null);
        
        Color minhaCor = new Color(255,228,225);
        getContentPane().setBackground(minhaCor);

        // listarUsuarios();
        // listarUsuariosLogados();
        this.flag = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBConcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCasdastro = new javax.swing.JMenu();
        jMenuItemUsuarioCadastro = new javax.swing.JMenuItem();
        jMenuItemClienteCadastro = new javax.swing.JMenuItem();
        jMenuItemPetCadastro = new javax.swing.JMenuItem();
        jMenuItemAdocoesCadastro = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemUsuarioEditar = new javax.swing.JMenuItem();
        jMenuItemPetEditar = new javax.swing.JMenuItem();
        jMenuItemClienteEditar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        relatorio = new javax.swing.JMenu();
        jMenuItemRelatorio = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Inicial");
        setBackground(new java.awt.Color(255, 228, 225));

        jPanel1.setBackground(new java.awt.Color(255, 228, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SYSPET", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/patas.png"))); // NOI18N
        jLabel1.setText("Bem Vindo");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Sistema de Gestão para Instituições de Adoção Animal");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/syspet2.1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(126, 126, 126))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBConcluir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBConcluir.setText("Fechar");
        jBConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcluirActionPerformed(evt);
            }
        });

        jLabel3.setText("Devolped By: Creative Code ");

        jMenuCasdastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        jMenuCasdastro.setText("Cadastros");

        jMenuItemUsuarioCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add-user.png"))); // NOI18N
        jMenuItemUsuarioCadastro.setText("Usuário");
        jMenuItemUsuarioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioCadastroActionPerformed(evt);
            }
        });
        jMenuCasdastro.add(jMenuItemUsuarioCadastro);

        jMenuItemClienteCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add-cliente.png"))); // NOI18N
        jMenuItemClienteCadastro.setText("Cliente");
        jMenuItemClienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteCadastroActionPerformed(evt);
            }
        });
        jMenuCasdastro.add(jMenuItemClienteCadastro);

        jMenuItemPetCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add-pet.png"))); // NOI18N
        jMenuItemPetCadastro.setText("Pet");
        jMenuItemPetCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPetCadastroActionPerformed(evt);
            }
        });
        jMenuCasdastro.add(jMenuItemPetCadastro);

        jMenuItemAdocoesCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add-adocao.png"))); // NOI18N
        jMenuItemAdocoesCadastro.setText("Adoções");
        jMenuItemAdocoesCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdocoesCadastroActionPerformed(evt);
            }
        });
        jMenuCasdastro.add(jMenuItemAdocoesCadastro);

        jMenuBar1.add(jMenuCasdastro);

        jMenuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listar.png"))); // NOI18N
        jMenuEditar.setText("Alterações");

        jMenuItemUsuarioEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listas.png"))); // NOI18N
        jMenuItemUsuarioEditar.setText("Usuário");
        jMenuItemUsuarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioEditarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemUsuarioEditar);

        jMenuItemPetEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listas.png"))); // NOI18N
        jMenuItemPetEditar.setText("Pet");
        jMenuItemPetEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPetEditarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemPetEditar);

        jMenuItemClienteEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listas.png"))); // NOI18N
        jMenuItemClienteEditar.setText("Cliente");
        jMenuItemClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteEditarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemClienteEditar);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/listas.png"))); // NOI18N
        jMenuItem3.setText("Adoção");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItem3);

        jMenuBar1.add(jMenuEditar);

        relatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        relatorio.setText("Relatorio");

        jMenuItemRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gerar-relatorio.png"))); // NOI18N
        jMenuItemRelatorio.setText("Relatorio");
        jMenuItemRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioActionPerformed(evt);
            }
        });
        relatorio.add(jMenuItemRelatorio);

        jMenuBar1.add(relatorio);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("Tela Inicial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(181, 181, 181)
                .addComponent(jBConcluir)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConcluir)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUsuarioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioCadastroActionPerformed
        // TODO add your handling code here:
        jfrmCadastroUsuario cadastroUsuario = new jfrmCadastroUsuario();
        cadastroUsuario.show();
    }//GEN-LAST:event_jMenuItemUsuarioCadastroActionPerformed
    
    
    
    private void jBConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcluirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBConcluirActionPerformed

    private void jMenuItemUsuarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioEditarActionPerformed
        // TODO add your handling code here:
        jfrmEditarUsuario editarUsuario = new jfrmEditarUsuario();
        editarUsuario.show();
    }//GEN-LAST:event_jMenuItemUsuarioEditarActionPerformed

    private void jMenuItemRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioActionPerformed
        // TODO add your handling code here:

        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        Date data = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd_MM_yyyy");
        String dataAtual = String.valueOf(formatador.format(data));
        try {
            PdfWriter.getInstance(document, new FileOutputStream("Relatório " + dataAtual + ".pdf"));
            Font fontNegrita = new Font(Font.FontFamily.HELVETICA, 5, Font.BOLD);
            Font fontNegritaP = new Font(Font.FontFamily.HELVETICA, 9, Font.BOLD);
            Font font = new Font(Font.FontFamily.HELVETICA, 8);
            Font fontConteudoTabela = new Font(Font.FontFamily.HELVETICA, 5);

            document.open();
            document.setPageSize(PageSize.A3);
            Paragraph titulo = new Paragraph("TITULO", fontNegritaP);
            Paragraph subtitulo = new Paragraph("SUBTITULO", font);
            titulo.setAlignment(Element.ALIGN_CENTER);
            subtitulo.setAlignment(Element.ALIGN_CENTER);

            document.add(titulo);
            document.add(subtitulo);
            document.add(new Paragraph("\n"));

            PdfPTable tabela = new PdfPTable(new float[]{60f, 40f, 20f});
            tabela.setTotalWidth(550);
            tabela.setLockedWidth(true);

            PdfPCell c1 = new PdfPCell(new Phrase("COLUNA 1", fontNegrita));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabela.addCell(c1);

            c1 = new PdfPCell(new Phrase("COLUNA 2", fontNegrita));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabela.addCell(c1);

            c1 = new PdfPCell(new Phrase("COLUNA 3", fontNegrita));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabela.addCell(c1);

            ArrayList<Login> loginArray = new ArrayList<Login>();

            LoginDao loginDao = new LoginDao();
            try {
                loginArray = loginDao.listar("");
            } catch (Exception ex) {
                Logger.getLogger(jfrmTelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }

            for (int i = 0; i < loginArray.size(); i++) {

                PdfPCell c = new PdfPCell(new Phrase(String.valueOf(loginArray.get(i).getId()), fontConteudoTabela));
                c.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabela.addCell(c);

                c = new PdfPCell(new Phrase(loginArray.get(i).getUsuario(), fontConteudoTabela));
                c.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabela.addCell(c);

                c = new PdfPCell(new Phrase("Coluna 3", fontConteudoTabela));
                c.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabela.addCell(c);

            }
            document.add(tabela);
            document.add(new Paragraph("\n"));
            Paragraph emicao = new Paragraph("EMISSÃO: " + dataAtual, font);
            emicao.setAlignment(Element.ALIGN_RIGHT);
            document.add(new Paragraph(emicao));
            document.close();

        } catch (DocumentException ex) {
            System.out.println("Error:" + ex);
        } catch (FileNotFoundException ex) {
            System.out.println("Error:" + ex);
        } finally {
            document.close();
        }

        try {
            Desktop.getDesktop().open(new File("Relatório " + dataAtual + ".pdf"));
        } catch (IOException ex) {
            System.out.println("Error:" + ex);
        }


    }//GEN-LAST:event_jMenuItemRelatorioActionPerformed

    private void jMenuItemPetCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPetCadastroActionPerformed
        // TODO add your handling code here:
        jfrmCadastroPet cadastroPet = new jfrmCadastroPet();
        cadastroPet.show();
    }//GEN-LAST:event_jMenuItemPetCadastroActionPerformed

    private void jMenuItemAdocoesCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdocoesCadastroActionPerformed
        jfrmCadastrarAdocao cadastroDoacao = new jfrmCadastrarAdocao();
        cadastroDoacao.show();
    }//GEN-LAST:event_jMenuItemAdocoesCadastroActionPerformed

    private void jMenuItemClienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteCadastroActionPerformed
        jfrmCadastrarCliente cadastroCliente = new jfrmCadastrarCliente();
        cadastroCliente.show();
    }//GEN-LAST:event_jMenuItemClienteCadastroActionPerformed

    private void jMenuItemPetEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPetEditarActionPerformed
        jfrmEditarPet editarPet = new jfrmEditarPet();
        editarPet.show();
    }//GEN-LAST:event_jMenuItemPetEditarActionPerformed

    private void jMenuItemClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteEditarActionPerformed
        jfrmEditarCliente editarCliente = new jfrmEditarCliente();
        editarCliente.show();
    }//GEN-LAST:event_jMenuItemClienteEditarActionPerformed


    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdocaoEditarActionPerformed
      jfrmEditarAdocao editarAdocao = new jfrmEditarAdocao();
        editarAdocao.show();
    }//GEN-LAST:event_jMenuItemAdocaoEditarActionPerformed

    private void jMenuItemAdocaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    
    }//GEN-LAST:event_jMenuItem3ActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCasdastro;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAdocoesCadastro;
    private javax.swing.JMenuItem jMenuItemClienteCadastro;
    private javax.swing.JMenuItem jMenuItemClienteEditar;
    private javax.swing.JMenuItem jMenuItemPetCadastro;
    private javax.swing.JMenuItem jMenuItemPetEditar;
    private javax.swing.JMenuItem jMenuItemRelatorio;
    private javax.swing.JMenuItem jMenuItemUsuarioCadastro;
    private javax.swing.JMenuItem jMenuItemUsuarioEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu relatorio;
    // End of variables declaration//GEN-END:variables
    
}




