/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author leehr
 */
public class jfrmEditarPet extends javax.swing.JFrame {

    /**
     * Creates new form jfrmEditarPet
     */
    public jfrmEditarPet() {
        initComponents();

        try {
            PetDao pt = new PetDao();
            pets = pt.listar("");
            for (Pet p : pets) {
                DefaultTableModel model = (DefaultTableModel) tbPet.getModel();
                Object linha[] = new Object[]{p.getId(), p.getRaca(), p.getSexo(), p.getIdade(), p.getPeso(), p.getVacinas()};
                model.addRow(linha);
    }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao listar Pet.");
        }
        
        Color minhaCor = new Color(255,228,225);
        getContentPane().setBackground(minhaCor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        dispose();
    }                                          

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {                                          
         if (tbPet.getSelectedRow() > -1) {
            try {
                Object selectedObject = (Object) tbPet.getModel().getValueAt(tbPet.getSelectedRow(), 1);
                PetDao pd = new PetDao();
                Pet p;
                int teste = 0;
                
                p = pd.listar(selectedObject.toString(), teste);
                jfrmAlterarPet altera = new jfrmAlterarPet(this);
                
                //altera.setId(p.getId());
                altera.jtxtRaca.setText(p.getRaca());
                altera.jtxtSexo.setText(p.getSexo());
                altera.jtxtIdade.setText(Integer.toString(p.getIdade()));
                altera.jtxtPeso.setText(Double.toString(p.getPeso()));
                altera.jtxtVacina.setText(p.getVacinas());
                
                //altera.show();
                

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Falha ao preencher formulário!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para continuar!");
        }
    }                                         

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {                                              
        fillTable();
    }                                             

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (tbPet.getSelectedRow() > -1) {
            try {

                Object selectedObject = (Object) tbPet.getModel().getValueAt(tbPet.getSelectedRow(), 1);

                PetDao lg = new PetDao();

                Pet l;
                int teste = 1;
                l = lg.listar(selectedObject.toString(), teste);
                lg.deletar(l);
                ArrayList<Pet> newArrayList = new ArrayList<Pet>();
                for (Pet pt : pets) {
                    if (l.getId() != pt.getId()) {
                        newArrayList.add(pt);
                    }
                }
                pets = newArrayList;
                JOptionPane.showMessageDialog(null, "Dados Excluidos!");

                atualizaTabela();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Falha ao deletar Pet!" );
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para continuar!");
        }
    }                                         

    private void fillTable() {
        try {
            ArrayList<Pet> loginMatch = new ArrayList<Pet>(); //= ad.listar(jTextFieldPesquisa.getText());
            JTableController.limpaJTable(tbPet);
            for (Pet p : pets) {
                if (p.getRaca().toLowerCase().startsWith(jTextFieldPesquisa.getText().toLowerCase())) {
                    loginMatch.add(p);
                }
            }
            for (Pet pt : loginMatch) {
                DefaultTableModel model = (DefaultTableModel) tbPet.getModel();
                Object linha[] = new Object[]{pt.getId(), pt.getRaca(), pt.getSexo(), pt.getIdade(), pt.getPeso(), pt.getVacinas()};
                model.addRow(linha);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao listar Pet.");
        }

    }

    public void atualizaTabela() {
        try {

            DefaultTableModel modelExcluir = (DefaultTableModel) tbPet.getModel();
            while (modelExcluir.getRowCount() > 0) {
                modelExcluir.removeRow(0);
            }
            PetDao pt = new PetDao();
            pets = pt.listar("");
            for (Pet pts : pets) {
                DefaultTableModel model = (DefaultTableModel) tbPet.getModel();
                Object linha[] = new Object[]{pts.getId(), pts.getRaca(), pts.getSexo(), pts.getIdade(), pts.getPeso(), pts.getVacinas()};
                model.addRow(linha);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao listar Pet.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmEditarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmEditarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmEditarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmEditarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmEditarPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
